import Link from "next/link";
import Image from "next/image";
import { ArrowRight, Award } from "lucide-react";
import site from "@/data/site.json";
import projects from "@/data/projects.json";
import { ActionCard, ProjectCard } from "@/components/cards";

export default function Home() { return <><section className="home-hero"><div className="container home-hero-grid"><div className="home-hero-copy"><div className="eyebrow">Researcher · Chartered Accountant · Principal Investigator</div><h1 className="serif" style={{fontSize:"clamp(3.2rem,7vw,6.6rem)",lineHeight:.95,margin:"22px 0"}}>Chinyere<br/><span style={{color:"var(--gold)"}}>Chidera Okechukwu.</span></h1><p style={{fontSize:20,lineHeight:1.6,maxWidth:650,color:"#d1dbe7"}}>{site.hero}</p><div style={{display:"flex",gap:12,marginTop:30,flexWrap:"wrap"}}><Link className="button" style={{background:"var(--gold)",color:"var(--navy)"}} href="/research">Explore research <ArrowRight size={17}/></Link><Link className="button" style={{border:"1px solid #708197"}} href="/contact">Start a conversation</Link></div></div><div className="home-portrait-frame"><div className="home-portrait-glow"/><Image src="/brand/chinyere-portrait.png" alt="Chinyere Chidera Okechukwu, ESG and sustainability researcher" width={1024} height={1536} priority sizes="(max-width: 720px) min(82vw, 430px), (max-width: 1100px) 38vw, 440px" className="home-portrait"/></div></div></section>
<section className="section"><div className="container"><div className="eyebrow">Research dashboard</div><div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",marginTop:22}}>{site.metrics.map(m=><div className="card" key={m.label}><div className="serif" style={{fontSize:40,color:"var(--gold)"}}>{m.value}</div><div>{m.label}</div></div>)}</div></div></section>
<section className="section" style={{background:"var(--mist)"}}><div className="container"><div className="eyebrow">Selected work</div><h2 className="serif" style={{fontSize:42,maxWidth:620,margin:"12px 0 30px"}}>Building a more trusted information infrastructure for sustainable organisations.</h2><div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))"}}>{projects.slice(0,3).map(p=><ProjectCard key={p.title} item={p}/>)}</div></div></section>
<section className="section"><div className="container"><div className="grid" style={{gridTemplateColumns:"repeat(auto-fit,minmax(220px,1fr))"}}><ActionCard title="Publications" description="Scholarly work on ESG, AI, information and systems thinking." href="/publications"/><ActionCard title="Speaking" description="International conference contributions and knowledge exchange." href="/speaking" icon="calendar"/><ActionCard title="Leadership & service" description="Research leadership, peer review and social impact." href="/leadership-service"/></div></div></section>
<section className="section" style={{background:"var(--navy)",color:"white"}}><div className="container"><Award color="var(--gold)"/><h2 className="serif" style={{fontSize:42,maxWidth:770,margin:"16px 0"}}>“Sustainable transformation begins with trusted information, responsible leadership and evidence-based decision-making.”</h2><p style={{color:"#c8d3e1"}}>A portfolio connecting rigorous scholarship to practical organisational change.</p></div></section></>; }
